language: ruby

sudo: false

rvm: 1.9.3

script: $TEST_COMMAND

env:
  global:
    - USE_SAUCE=true
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - TEST_COMMAND="bash travis-core-script.sh"
    - JASMINE_BROWSER="firefox"
    - SAUCE_OS="Linux"
    - SAUCE_BROWSER_VERSION=''
    - secure: WSPWhlnC4mWSnSPquX+m1/BCu5ch5NygkaHuM2Nea7lD8oS3XLX8QncZZAsQ4lnNfqoDDuBOizG0AESiqNvE4y6x5qvLLTS6q+ce255ZEMZ71TBdZgDEEvGMEjOPPsVXiXyTQOP1lwOPlrbZvaPgWV7e11KIBab6DfFcQpnvDgo=
    - secure: SW7CJhZnwaNT749Gdnhvqb5rbXlAOsygUAzh9qhtyvbqXKkmJdBIEsO01YF6pbju1X2twE9JvWCOxeZju43NgQChJlPsGbjY2j3k/TdQeTAJesQe2K7ytwghunI30gjEovtRH0T3w1EmcKPH8yj5eBIcB2OYoJHx8KEC7e68q1g=

matrix:
  include:
    - env:
      - USE_SAUCE=false
      - TEST_COMMAND="bash travis-node-script.sh"
    - env:
      - JASMINE_BROWSER="safari"
      - SAUCE_OS="OS X 10.10"
      - SAUCE_BROWSER_VERSION=8
    - env:
      - JASMINE_BROWSER="safari"
      - SAUCE_OS="OS X 10.9"
      - SAUCE_BROWSER_VERSION=7
    - env:
      - JASMINE_BROWSER="safari"
      - SAUCE_OS="OS X 10.8"
      - SAUCE_BROWSER_VERSION=6
    - env:
      - JASMINE_BROWSER="safari"
      - SAUCE_OS="OS X 10.6"
      - SAUCE_BROWSER_VERSION=5
    - env:
      - JASMINE_BROWSER="internet explorer"
      - SAUCE_OS="Windows 8.1"
      - SAUCE_BROWSER_VERSION=11
    - env:
      - JASMINE_BROWSER="internet explorer"
      - SAUCE_OS="Windows 8"
      - SAUCE_BROWSER_VERSION=10
    - env:
      - JASMINE_BROWSER="internet explorer"
      - SAUCE_OS="Windows 7"
      - SAUCE_BROWSER_VERSION=9
    - env:
      - JASMINE_BROWSER="internet explorer"
      - SAUCE_OS="Windows 7"
      - SAUCE_BROWSER_VERSION=8
    - env:
      - JASMINE_BROWSER="chrome"
      - SAUCE_OS="Linux"
      - SAUCE_BROWSER_VERSION=''
    - env:
      - JASMINE_BROWSER="phantomjs"
      - USE_SAUCE=false
    - env:
      - USE_SAUCE=false
      - JASMINE_BROWSER="phantomjs"
      - TEST_COMMAND="bash travis-docs-script.sh"
