language: node_js
node_js:
  - "11"
  - "10"
  - "8"

script: $TEST_COMMAND

env:
  global:
    - USE_SAUCE=true
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - TEST_COMMAND="bash travis-core-script.sh"
    - secure: WSPWhlnC4mWSnSPquX+m1/BCu5ch5NygkaHuM2Nea7lD8oS3XLX8QncZZAsQ4lnNfqoDDuBOizG0AESiqNvE4y6x5qvLLTS6q+ce255ZEMZ71TBdZgDEEvGMEjOPPsVXiXyTQOP1lwOPlrbZvaPgWV7e11KIBab6DfFcQpnvDgo=
    - secure: SW7CJhZnwaNT749Gdnhvqb5rbXlAOsygUAzh9qhtyvbqXKkmJdBIEsO01YF6pbju1X2twE9JvWCOxeZju43NgQChJlPsGbjY2j3k/TdQeTAJesQe2K7ytwghunI30gjEovtRH0T3w1EmcKPH8yj5eBIcB2OYoJHx8KEC7e68q1g=

addons:
  sauce_connect: true

matrix:
  include:
    - env:
      - USE_SAUCE=false
      - TEST_COMMAND="npm test"
    - env:
      - USE_SAUCE=false
      - TEST_COMMAND="npm test"
    - env:
      - JASMINE_BROWSER="firefox"
      - SAUCE_OS="Linux"
      - SAUCE_BROWSER_VERSION=''
    - env:
      - JASMINE_BROWSER="safari"
      - SAUCE_OS="OS X 10.12"
      - SAUCE_BROWSER_VERSION=10
    - env:
      - JASMINE_BROWSER="safari"
      - SAUCE_OS="OS X 10.11"
      - SAUCE_BROWSER_VERSION=9
    - env:
      - JASMINE_BROWSER="safari"
      - SAUCE_OS="OS X 10.10"
      - SAUCE_BROWSER_VERSION=8
    - env:
      - JASMINE_BROWSER="MicrosoftEdge"
      - SAUCE_OS="Windows 10"
      - SAUCE_BROWSER_VERSION="15"
    - env:
      - JASMINE_BROWSER="internet explorer"
      - SAUCE_OS="Windows 8.1"
      - SAUCE_BROWSER_VERSION=11
    - env:
      - JASMINE_BROWSER="internet explorer"
      - SAUCE_OS="Windows 8"
      - SAUCE_BROWSER_VERSION=10
    - env:
      - JASMINE_BROWSER="chrome"
      - SAUCE_OS="Linux"
      - SAUCE_BROWSER_VERSION=''
    - env:
      - JASMINE_BROWSER="phantomjs"
      - USE_SAUCE=false
